api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import (FavoriteViewSet, IngredientViewSet, PurchaseViewSet,
                    SubscriptionViewSet)

router = routers.DefaultRouter()
router.register(
    r'favorites',
    FavoriteViewSet,
    basename='favorites'
)
router.register(
    r'ingredients',
    IngredientViewSet,
    basename='ingredients'
)
router.register(
    r'purchases',
    PurchaseViewSet,
    basename='purchases'
)
router.register(
    r'subscriptions',
    SubscriptionViewSet,
    basename='subscriptions'
)


urlpatterns = [
    path('v1/', include(router.urls)),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'recipes.views.page_not_found'
handler500 = 'recipes.views.server_error'


urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

recipes/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from pytils.translit import slugify

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название',
        help_text='Введите название ингредиента',
    )
    dimension = models.CharField(
        max_length=50,
        verbose_name='Единица измерения',
        help_text='Введите единицу измерения',
    )

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return f'{self.title}, {self.dimension}'


class Tag(models.Model):
    name = models.CharField(
        verbose_name='Имя',
        help_text='Введите имя тега',
        max_length=50,
        unique=True
    )
    color = models.CharField(
        verbose_name='Цвет',
        help_text='Введите цвет для тега',
        max_length=50
    )
    slug = models.SlugField(
        verbose_name='Тег',
        auto_created=True,
        help_text='Введите слаг для тега',
        unique=True
    )

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='recipes',
        help_text='Выберите автора рецепта'
    )
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Название рецепта',
        help_text='Укажите название рецепта'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Укажите подробное описание рецепта',
    )
    file = models.ImageField(
        verbose_name='Загрузить фото',
        help_text='Загрузите фото приготовленного рецепта',
        upload_to='recipes/'
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        verbose_name='Ингредиенты',
        through='IngredientRecipe',
        help_text='Выберите один или несколько ингредиентов',
        related_name='recipes'
    )
    tags = models.ManyToManyField(
        Tag,
        help_text='Выберите один или несколько ингредиентов тегов',
        verbose_name='Теги',
        related_name='recipes'
    )
    cooking_time = models.IntegerField(
        validators=[MinValueValidator(limit_value=1)],
        verbose_name='Время приготовления',
        help_text='Время приготовления в минутах'
    )
    slug = models.SlugField(
        verbose_name='Ссылка',
        auto_created=True,
        help_text=(
            'Заполняется автоматически по названию рецепта'
        )
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.title

    def list_tags(self):
        return self.tags.values_list('name', flat=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class IngredientRecipe(models.Model):
    ingredient = models.ForeignKey(
        Ingredient,
        verbose_name='Название',
        on_delete=models.CASCADE,
        related_name='ingredientsrecipe'
    )
    recipe = models.ForeignKey(
        Recipe,
        verbose_name='Рецепт',
        on_delete=models.CASCADE,
        related_name='ingredientsrecipe'
    )
    amount = models.DecimalField(
        verbose_name='Количество',
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(float('0.01'))]
    )

    def __str__(self):
        return (f'{self.recipe.title} содержится {self.ingredient.title} '
                f'в количестве {self.amount}')


class Subscription(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        on_delete=models.CASCADE,
        related_name='follower',
        help_text='Подписчик',
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following',
        help_text='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        unique_together = ['user', 'author']

    def __str__(self):
        return (f'{self.user.username} подписан на автора: '
                f'{self.author.username}')

    @property
    def has_following(self):
        return self.author.following.filter(
            user__id=self.user.id).exists()


class Purchase(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='purchases',
        help_text='Покупки пользователя'
    )
    recipe = models.ForeignKey(
        Recipe,
        verbose_name='Рецепт',
        on_delete=models.CASCADE,
        related_name='purchases',
        help_text='Добавленные к покупке рецепты'
    )

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        unique_together = ['user', 'recipe']
        ordering = ('-recipe__pub_date',)

    def __str__(self):
        return f'{self.user.username} добавил в покупки: {self.recipe.title}'


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='favorites',
        help_text='Избранное пользователя',
    )
    recipe = models.ForeignKey(
        Recipe,
        verbose_name='Рецепт',
        on_delete=models.CASCADE,
        related_name='favorites',
        help_text='Добавленные в избранное рецепты'
    )

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'
        unique_together = ['user', 'recipe']
        ordering = ('-recipe__pub_date',)

    def __str__(self):
        return f'{self.user.username} добавил в избранное: {self.recipe.title}'

templates/authorRecipe.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ author.get_full_name }}
{% endblock %}

{% block header %}
{{ author.get_full_name }}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block tags %}
  {% include "includes/search_tags.html" with tags=tags active_tags=active_tags %}
{% endblock %}

{% block main_content %}
{% csrf_token %}

{% if user.is_authenticated and not is_author%}
  <div class="author-subscribe" data-author="{{ author.id }}">
  <p style="padding: 0 0 2em 0;">
  <button class="button button_style_light-blue button_size_subscribe" 
    name="subscribe" {% if not is_following %} data-out {% endif %}>
      {% if is_following %}
        Отписаться от автора
      {% else %}
        Подписаться на автора
      {% endif %}
  </button></p>
  </div>
{% endif %}
  <!--  Содержание страницы -->
  <div class="card-list">
      {% for recipe in page %}
          {% include "includes/recipe_item.html" with recipe=recipe %}
      {% endfor %}   
  </div>
  <!-- Вывод паджинатора -->
  {% if page.has_other_pages %}
    {% include "includes/paginator.html" with items=page paginator=paginator %}
  {% endif %}
{% endblock %}

{% block scripts %}
{% if user.is_authenticated %}
  <script src="{% static 'js/components/Subscribe.js' %}"></script>
{% endif %}
<script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
<script src="{% static 'authorRecipe.js' %}"></script>
{% endblock %}

templates/base.html
  <!-- Загрузка статики -->
<!doctype html>
<html lang="ru">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  {% block styles %}
  {% endblock %}
</head>

<body class="body">

  <header class="header">
    {% include 'includes/nav.html' %}
  </header>

  <main class="main container">
    <div class="main__header">
      <h1 class="main__title">
      {% block header %}
      {% endblock %}
      </h1>
      {% block tags %}
      {% endblock %}
    </div>
    {% block main_content %}
      <!-- Содержимое страницы -->
    {% endblock %}
  </main>  
  {% include 'includes/footer.html' %}
</body>
</html>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script> 
<script src="{% static 'js/api/Api.js' %}"></script>
{% if user.is_authenticated %}
  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>
{% endif %}

{% block scripts %}
{% endblock %}

templates/favorite.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Избранное
{% endblock %}

{% block header %}
Избранное
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block tags %}
  {% include "includes/search_tags.html" with tags=tags active_tags=active_tags %}
{% endblock %}

{% block main_content %}
{% csrf_token %}
  {% if not user.favorites.exists %}
    <div class="card-header">
      Начните добавлять рецепты в Избранное!<br> 
      Это можно сделать на Главной странице, 
      Странице автора или на Странице рецепта!
    </div>  
  {% endif %}
  <!--  Содержание страницы -->
  <div class="card-list">
      {% for recipe in page %}
        {% include "includes/recipe_item.html" with recipe=recipe.recipe %}
      {% endfor %}   
  </div>
  <!-- Вывод паджинатора -->
  {% if page.has_other_pages %}
      {% include "includes/paginator.html" with active_tags=active_tags items=page paginator=paginator %}
  {% endif %}
    
{% endblock %}

{% block scripts %}
  <script src="{% static 'favorite.js' %}"></script>
{% endblock %}

templates/formRecipe.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {% if is_author %}
    Редактирование рецепта
  {% else %}
    Создание рецепта
  {% endif %}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block header %}
  {% if is_author %}
    Редактирование рецепта
  {% else %}
    Создание рецепта
  {% endif %}
{% endblock %}

{% block main_content %}
{% load user_filters %}
<div class="form-container">
  <form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form__group">
      <label for="id_name" class="form__label">
          {{ form.title.field.label }}
          {% if not is_author and form.title.field.required %}
            <span class="required">
            <font color="red">*</font>
            </span>
          {% endif %}
      </label>
      <div class="form__field-group">
        {{ form.title|addclass:"form__input" }}
        <span class="form__error">
            {{ form.title.errors }}
        </span>
      </div>  
    </div>
    <div class="form__group">
      <p class="form__label">Теги
        {% if not is_author and form.tags.field.required %}
          <span class="required">
            <font color="red">*</font>
          </span>
        {% endif %}
      </p>
      <div class="form__field-group">
        <div class="tags">
          {% for tag in form.tags.field.choices.queryset.all %}
          <div class="tags__item">
            <input type="checkbox" name="tags" value = "{{ tag.slug }}" id="{{ tag.id }}" 
            class="tags__checkbox tags__checkbox_style_{{ tag.color }}"                             
            {% if tag in form.instance.tags.all %} checked {% endif %}/>
            <label for="id_{{ tag.slug }}" class="tags__label">
                {{ tag.name }}
            </label>
          </div>
          {% endfor %}
        </div>
        <span class="form__error">
            {{ form.tags.errors }}
        </span>
      </div>
    </div>
    <div class="form__group">
      <label for="nameIngredient" class="form__label">
        Ингредиенты
        {% if not is_author and form.ingredients.field.required %}
          <span class="required">
            <font color="red">*</font>
          </span>
        {% endif %}
      </label>
        <div class="form__field-group">
          <div class="form__field-group-ingredientes">
            <div class="form__dropdown">
                <input type="text" id="nameIngredient" class="form__input">
                <div class="form__dropdown-items"></div>
            </div>
            <input type="number" id="cantidad" class="form__input" min="0">
            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
          </div>
          <div class="form__field-group-ingredientes-container">
            {% if is_author %}
            {% for ingredient in ingredientsrecipe %}
              <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                <span>
                  {{ ingredient.ingredient.title }} {{ ingredient.amount }} {{ ingredient.ingredient.dimension }}.
                </span>
                <span class="form__field-item-delete"></span>
                <input 
                    id="nameIngredient_{{ forloop.counter }}" 
                    name="nameIngredient_{{ forloop.counter }}" 
                    type="hidden" 
                    value="{{ ingredient.ingredient.title }}">
                <input 
                    id="valueIngredient_{{ forloop.counter }}"
                    name="valueIngredient_{{ forloop.counter }}"
                    type="hidden"
                    value="{{ ingredient.amount }}">
                <input
                    id="unitsIngredient_{{ forloop.counter }}"
                    name="unitsIngredient_ing_{{ forloop.counter }}"
                    type="hidden"
                    value="{{ ingredient.ingredient.dimension }}.">
              </div>
            {% endfor %}
            {% endif %}
            <span class="form__error">
              {{ form.non_field_errors }}
            </span>
          </div>
          <span class="form__ingredient-link" id="addIng">
            Добавить ингредиент
          </span>
        </div>
    </div>
    <div class="form__group">
      <label for="id_time" class="form__label">
        {{ form.cooking_time.field.label }}
        {% if not is_author and form.cooking_time.field.required %}
          <span class="required">
            <font color="red">*</font>
          </span>
        {% endif %}
      </label>
      <div class="form__field-group form__field-group_time">
        {{ form.cooking_time|addclass:"form__input" }}
        <label for="id_time" class="form__label">минут</label>
        <span class="form__error">
            {{ form.cooking_time.errors }}
        </span>
      </div>
    </div>
    <div class="form__group">
        <label for="id_description" class="form__label">
            {{ form.description.field.label }}
            {% if not is_author and form.description.field.required %}
            <span class="required">
              <font color="red">*</font>
            </span>
          {% endif %}
        </label>
        <div class="form__field-group">
            {{ form.description|addclass:"form__textarea" }}
            <span class="form__error">
                {{ form.description.errors }}
            </span>
        </div>
    </div>
    {% if is_author %}
        <div class="form__group">
            <span class="form__label">
                {{ form.file.field.label }}
            </span>
            <div class="form__field-group">
                {{ form.file }}
                <span class="form__error">
                    {{ form.file.errors }}
                </span>
            </div>
        </div>
        <div class="form__footer">
            <button type="submit" class="button button_style_blue">
                Сохранить
            </button> 
            <a style="margin-left: 2.5em" 
            href="{% url 'recipe_delete' recipe.slug %}" 
            class="form__ingredient-link">
                Удалить
            </a>
        </div>
    {% else %}
        <div class="form__group">
            <span class="form__label">
              {{ form.file.field.label }}
              {% if form.description.field.required %}
              <span class="required">
                <font color="red">*</font>
              </span>
              {% endif %}
            </span>
            <div class="form__field-group">
                {{ form.file }}
                <span class="form__error">
                  {{ form.file.errors }}
                </span>
            </div>
        </div>
        <div class="form__footer">
            <button type="submit" class="button button_style_blue">
            Создать рецепт
        </button>
        </div>
    {% endif %}
  </form>
</div>
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/utils/debouncing.js' %}"></script>
  <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Рецепты
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block header %}
Рецепты
{% endblock %}

{% block tags %}
  {% include "includes/search_tags.html" with tags=tags active_tags=active_tags %}
{% endblock %}

{% block main_content %}
{% csrf_token %}

  <!--  Содержание страницы -->
  <div class="card-list">
      {% for recipe in page %}
        {% include "includes/recipe_item.html" with recipe=recipe %}
      {% endfor %}   
  </div>
  <!-- Вывод паджинатора -->
  {% if page.has_other_pages %}
      {% include "includes/paginator.html" with active_tags=active_tags items=page paginator=paginator %}
  {% endif %}
    
{% endblock %}

<hidden>
{% block scripts %}
  {% if user.is_authenticated %}
    <script src="{% static 'indexAuth.js' %}"></script>
  {% else %}
    <script src="{% static 'indexNotAuth.js' %}"></script>
  {% endif%}
{% endblock %}
</hidden>

templates/myFollow.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Мои подписки
{% endblock %}

{% block header %}
Мои подписки
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}



{% block main_content %}
{% csrf_token %}

<!--  Содержание страницы -->
<div class="card-list">
    {% for author in page %}
      {% include "includes/subs_card_user.html" with author=author %}
    {% endfor %}
</div>
<!-- Вывод паджинатора -->
{% if page.has_other_pages %}
    {% include "includes/paginator.html" with items=page paginator=paginator %}
{% endif %}

{% endblock %}

{% block scripts %}   
  <script src="{% static 'js/components/Subscribe.js' %}"></script>
  <script src="{% static 'js/components/MyFollow.js' %}"></script>
  <script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

templates/shopList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Список покупок
{% endblock %}

{% block header %}
Список покупок
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}


{% block main_content %}
{% csrf_token %}

<!--  Содержание страницы -->
<div class="card-list card-list_column">
  <ul class="shopping-list">
    {% for recipe in page %}
      {% include "includes/shop_list_item.html" with recipe=recipe %}
    {% endfor %}
    
    {% if user.purchases.exists %}
      <a href="{% url 'purchases_download' %}">
        <button class="button button_style_blue">
          Скачать список
        </button>                 
      </a>
    {% else %}
      <div class="card-header">
        Начните добавлять рецепты в Список покупок!<br> 
        Это можно сделать на Главной странице, 
        Странице автора или на Странице рецепта!
      </div>
    {% endif %}
  </ul>
</div>
<!-- Вывод паджинатора -->
{% if page.has_other_pages %}
    {% include "includes/paginator.html" with items=page paginator=paginator %}
{% endif %}

{% endblock %}

{% block scripts %}   
  <script src="{% static 'js/components/ShopList.js' %}"></script>
  <script src="{% static 'shopList.js' %}"></script>
{% endblock %}

templates/singlePage.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load app_tags %}

{% block title %}
{{ recipe.title }}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}



{% block main_content %}
{% csrf_token %}
<div class="single-card" data-id="{{recipe.id}}" 
  data-author="{{recipe.author.id}}">
  {% include "includes/image.html" with filename=recipe.file class="single-card__image" %}
    <div class="single-card__info">
      <div class="single-card__header-info">
        <h1 class="single-card__title">
          {{ recipe.title }}
        </h1>
        <div class="single-card__favorite">
          {% if user.is_authenticated and recipe|has_favorite:user %} 
            <button class="button button_style_none" name="favorites">
              <span class="icon-favorite icon-favorite_big icon-favorite_active">
              </span>
            </button>
            <div class="single-card__favorite-tooltip tooltip">
              Убрать из избранное
            </div>
          {% elif user.is_authenticated %}
            <button class="button button_style_none" name="favorites" data-out>
              <span class="icon-favorite icon-favorite_big"></span>
            </button>
            <div class="single-card__favorite-tooltip tooltip">
              Добавить в избранное
            </div>
          {% endif %}
        </div>
      </div>
      <ul class="single-card__items">
          {% for tag in recipe.tags.all %}
            <li class="single-card__item">
              <span class="badge badge_style_{{ tag.color }}">
              {{ tag.name }}
            </span></li>
          {% endfor %}
      </ul>
      <div class="single-card__items single-card__items_column">
          <p class="single-card__text">
            <span class="icon-time"></span>
            {{ recipe.cooking_time }} мин.
          </p>
          <ul class="single-card__items">
              <li class="single-card__item" >
                <p class="single-card__text">
                  <span class="icon-user"></span> 
                  <a href="{% url 'profile' recipe.author %}">
                    {{ recipe.author }}
                  </a>
                </p>
              </li>
              {% if is_author %}
              <li class="single-card__item">
                <a style="margin-left: 2.5em" 
                  href="{% url 'recipe_edit' recipe.slug %}" 
                  class="single-card__text">
                  Редактировать рецепт
                </a>
              </li>
              {% endif %}
          </ul>
      </div>
      <ul class="single-card__items">
        {% if user.is_authenticated %}
          <li class="single-card__item">
            <button class="button button_style_blue" name="purchases" 
            {% if not is_purchassing %} data-out {% endif %}>
            {% if is_purchassing %}
              Удалить из покупок
            {% else %}
            <span class="icon-plus"></span> 
              Добавить в покупки
            {% endif %}
        {% endif %}
  
          </button></li>
          <li class="single-card__item">
            {% if user.is_authenticated and not is_author %}
              <button class="button button_style_light-blue button_size_subscribe" 
              name="subscribe" {% if not is_following %} data-out {% endif %}>
                {% if is_following %}
                  Отписаться от автора
                {% else %}
                  Подписаться на автора
                {% endif %}
              </button>
            {% endif %}
          </li>
      </ul>
      <div class="single-card__section">
        <h3 class="single-card__section-title">Ингредиенты:</h3>
        <div class="single-card__items single-card__items_column">
          {% for ir in ingredientsrecipe %}
          <p class=" single-card__section-item">
            {{ ir.ingredient.title }} - {{ ir.amount }} {{ ir.ingredient.dimension }}.
          </p>
          {% endfor %}
        </div>
      </div>
      <div class="single-card__section">
        <h3 class="single-card__section-title">Описание:</h3>
        <p class=" single-card__section-text">{{ recipe.description }}</p>
      </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/components/SingleCard.js' %}"></script>
  {% if user.is_authenticated %}
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'singlePage.js' %}"></script>
  {% else %}
    <script src="{% static 'singlePageNotAuth.js' %}"></script>
  {% endif %}
{% endblock %}